### ISSUE TITLE
Improve entity interaction

### ISSUE THREAD

**Issue by p-lahanas** [UQcsse3200/2023-studio-1#337]
# **Description**
Current interaction design will not scale well as more entities are added with interacting abilities. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Rework player actions and Interaction Detector (Sep. 18)

**Completion Deadline:** Sep 18

# **Members**
Peter Lahanas (@p-lahanas)

**Comment by pchsa** [comment]
I think i see the motivation for this, in that you want to only detect the entities you need to minimise the size of entitiesInRange. I think compared to other systems in the game engine, the cost of just detecting every entity in the given range and filtering them after is pretty small. But this change does make it slightly more efficient. However, this change introduces coupling, as it only includes entity types that the player interacts with. I know the wiki is poorly named and i put it in a bad spot (player folder), but if u look at what the component does, it actually provides functionality for anything with a range. For example, if you were intending for sprinker / light source to be circular, it can be used to detect crop tiles to water / light? them. We are planning to use this component on hostiles. It also increases code maintenance, like if more animals were added to the game, it would have to be added in the component.

I do agree the changes improve some parts of the component, but i do have some suggestions to consider.
1. Consider using the existing PhysicsLayer to filter entities, it uses bitwise AND so is even more efficient if u are particular about that. It would also reduce code maintenance, since e.g. every NPC would already be set to this layer so it wouldnt have to be added. But i guess i do understand that you may not want every entity in a layer to be interactable.
2. Make a function / constructor setDetectableEntities/Layers(). This makes is so that the component isnt coupled to just what the player interacts with.

**Comment by JTrenerry** [comment]
> I think i see the motivation for this, in that you want to only detect the entities you need to minimise the size of entitiesInRange. I think compared to other systems in the game engine, the cost of just detecting every entity in the given range and filtering them after is pretty small. But this change does make it slightly more efficient. However, this change introduces coupling, as it only includes entity types that the player interacts with. I know the wiki is poorly named and i put it in a bad spot (player folder), but if u look at what the component does, it actually provides functionality for anything with a range. For example, if you were intending for sprinker / light source to be circular, it can be used to detect crop tiles to water / light? them. We are planning to use this component on hostiles. It also increases code maintenance, like if more animals were added to the game, it would have to be added in the component.
> 
> I do agree the changes improve some parts of the component, but i do have some suggestions to consider.
> 
>     1. Consider using the existing PhysicsLayer to filter entities, it uses bitwise AND so is even more efficient if u are particular about that. It would also reduce code maintenance, since e.g. every NPC would already be set to this layer so it wouldnt have to be added. But i guess i do understand that you may not want every entity in a layer to be interactable.
> 
>     2. Make a function / constructor setDetectableEntities/Layers(). This makes is so that the component isnt coupled to just what the player interacts with.

Hey, thanks for your input we will most likely just make a new component or add new functions to this but yeah just saw Team 2 use it for interactions with quests and all that so I assumed it was just for the player, will most likely either make a new component for players or make new functions in this, PhysicsLayer does not work for us as it will change other code that needs to be the way it is, water and sprinklers won't use this component. But overall I think we do want it to just be coupled with what the player interacts with so we will move it else where.

**Comment by pchsa** [comment]
Ok let me know what changes you make cause i also use this component for the player feeding animals.

**Comment by JTrenerry** [comment]
> Ok let me know what changes you make cause i also use this component for the player feeding animals.

pretty sure feeding animals works still.

**Comment by JTrenerry** [comment]
#342
